spring.datasource.url=jdbc:postgresql://localhost:5433/springdb
spring.datasource.username=ghofrane
spring.datasource.password=ghof123*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect